/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.checkerframework.checker.units.qual.A;
import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.utils.UserServiceUtil;

import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System ");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }
        catch(IOException e){
            System.out.println("There is something went wrong");
            return;
        }
        while(option != 7){
            System.out.println("Choose an option");
            System.out.println("1. Sign Up");
            System.out.println("2. Login In");
            System.out.println("3. Fetch Booking");
            System.out.println("4.Search Train");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit");

            option = sc.nextInt();
            switch(option){
                case 1:
                    System.out.println("Enter the username to Sign up");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter the password to sign up");
                    String passwordToSignUp = sc.next();

                    User usertoSignUp = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(), UUID.randomUUID().toString());

                    userBookingService.signUp(usertoSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username to Login");
                    String name = sc.next();
                    System.out.println("Enter the password to Login");
                    String password = sc.next();
                    User userToLogin =  new User(name, password,UserServiceUtil.hashPassword(password),new ArrayList<>(),UUID.randomUUID().toString());

                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }
                    catch(IOException ex) {
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching Your Bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:

                    System.out.println("Search Train");
                    System.out.println("Type your source station");
                    String source = sc.next();
                    System.out.println("Type your destination");
                    String dest = sc.next();

                    List<Train> trains = userBookingService.getTrain(source,dest);

                    int index =1;
                    for(Train t: trains){
                        System.out.println(index+"Train id : " +t.getTrainId());
                        for(Map.Entry<String,String> entry : t.getStationTimes().entrySet()){
                            System.out.println("station" + entry.getKey() + " time: " + entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                      trainSelectedForBooking = trains.get(sc.nextInt());
                    break;

                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer> row : seats){
                        for(Integer val :row){
                            System.out.println(val + " ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select you seat by typing row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your tickets...");
                    boolean booked = userBookingService.BookTrainSeat(trainSelectedForBooking,row,col);
                    if(booked){
                        System.out.println("Your ticket has been booked ");
                    }
                    else{
                        System.out.println("Can't book this ticket");
                    }
                    break;

                default:
                    break;

            }


        }

    }
}
